services:
  web:
    image: odoo:18.0
    container_name: ${ODOO_CONTAINER_NAME}  
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo18-web-data:/var/lib/odoo
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
  db:
    image: postgres:16
    container_name: ${PG_CONTAINER_NAME}
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo18-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
volumes:
  odoo18-web-data:
  odoo18-db-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass
